site_name: BYU CCE Drone Measurements
site_url: https://byu-cce_drone_measurements.readthedocs.io/en/latest/
site_description: Course materials for the CCE class at BYU
site_author: Instructors and TAs of the CCE class at BYU
repo_url: https://github.com/byu-cce-drones/content/
#favicon: 'images/favicon.ico'
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/mathjax-config.js
extra_css:
  - css/custom.css
markdown_extensions:
    - attr_list
    - sane_lists
    - md_in_html
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.tasklist:
        custom_checkbox: false
        clickable_checkbox: true
    - pymdownx.emoji:

theme:
  name: readthedocs
  logo: images/class_logo.png

nav:
  - Home: index.md

  - Class Resources:
          - Syllabus: class_resources/syllabus.md
          - Grading Policy: class_resources/grading_policy.md
          - Teaching Assistants (TAs):
                  - About the TAs: class_resources/ta/tas.md
                  - Office Hours: class_resources/ta/ta_hours.md
          - Flight Checklist:
              - Pre-Flight Checklist:
                  - General Checklist: class_resources/flight_check_list/pre_flight/pre_general.md
              - Post-Flight Checklist:
                  - General Checklist: class_resources/flight_check_list/post_flight/post_general.md

  - Readings:
          - Class Overview: gen_reading/class_overview.md
          - Metadata: gen_reading/metadata.md
          - Mission Planning: gen_reading/mission_planning_sfm.md
          - SfM Workflow: gen_reading/sfm_workflow.md
          - LiDAR Imaging: gen_reading/lidar.md
          - Thermal Imaging: gen_reading/thermal.md
          - Multispectral Imaging: gen_reading/multispectral.md

  - Software:
      - QGIS: software/qgis.md
      - Bentley: software/bentley_itwin.md

  - Labs:
        - Measurement: labs/lab_measurement.md

  - FAA Part 107 License:
        - Exam Planning & Overview: part_107_license/faa_exam_planning_and_overview.md
        - Knowledge Review: part_107_license/part_107_knowledge_review.md
        - Part 107 Study Resources: part_107_license/part_107_resources.md
        - Mini Practice Exam: part_107_license/mini_exam.md
        - Mini Exam Key (Instructor): part_107_license/mini_exam_instructor_version.md
        - Full Practice Exam (60 Q): part_107_license/60_question_exam.md
        - Full Exam Key (Instructor): part_107_license/60_question_exam_instructor_key.md

  - Final Project:
        - Overview: final_project/overview.md
        - Project Proposal: final_project/proposal.md
        - Flight and Data Processing: final_project/flight_and_processing.md
        - Project Presentation: final_project/presentation.md
        - Final Report: final_project/report.md